/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers';
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface POBMinterV2Interface extends ethers.utils.Interface {
  functions: {
    'maxIndex()': FunctionFragment;
    'mint(address,uint256)': FunctionFragment;
    'mintableErc1155()': FunctionFragment;
    'owner()': FunctionFragment;
    'pobMinterV1()': FunctionFragment;
    'pricingCurve(uint256)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setTreasury(address)': FunctionFragment;
    'tokenIdToTxHash(uint256)': FunctionFragment;
    'tokenType()': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'treasury()': FunctionFragment;
    'txHashToTokenId(uint256)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'maxIndex', values?: void): string;
  encodeFunctionData(
    functionFragment: 'mint',
    values: [string, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'mintableErc1155',
    values?: void,
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: void): string;
  encodeFunctionData(functionFragment: 'pobMinterV1', values?: void): string;
  encodeFunctionData(
    functionFragment: 'pricingCurve',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: void,
  ): string;
  encodeFunctionData(functionFragment: 'setTreasury', values: [string]): string;
  encodeFunctionData(
    functionFragment: 'tokenIdToTxHash',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'tokenType', values?: void): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'treasury', values?: void): string;
  encodeFunctionData(
    functionFragment: 'txHashToTokenId',
    values: [BigNumberish],
  ): string;

  decodeFunctionResult(functionFragment: 'maxIndex', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'mintableErc1155',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'pobMinterV1',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'pricingCurve',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setTreasury',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'tokenIdToTxHash',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'tokenType', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'txHashToTokenId',
    data: BytesLike,
  ): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
    'UpdatedRegistry(uint256,uint256)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UpdatedRegistry'): EventFragment;
}

export class POBMinterV2 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: POBMinterV2Interface;

  functions: {
    maxIndex(
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber;
    }>;

    mint(
      _dst: string,
      _txHash: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<ContractTransaction>;

    mintableErc1155(
      overrides?: CallOverrides,
    ): Promise<{
      0: string;
    }>;

    owner(
      overrides?: CallOverrides,
    ): Promise<{
      0: string;
    }>;

    pobMinterV1(
      overrides?: CallOverrides,
    ): Promise<{
      0: string;
    }>;

    pricingCurve(
      _maxIndex: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    setTreasury(
      _treasury: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    tokenIdToTxHash(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber;
    }>;

    tokenType(
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber;
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    treasury(
      overrides?: CallOverrides,
    ): Promise<{
      0: string;
    }>;

    txHashToTokenId(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<{
      0: BigNumber;
    }>;
  };

  maxIndex(overrides?: CallOverrides): Promise<BigNumber>;

  mint(
    _dst: string,
    _txHash: BigNumberish,
    overrides?: PayableOverrides,
  ): Promise<ContractTransaction>;

  mintableErc1155(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  pobMinterV1(overrides?: CallOverrides): Promise<string>;

  pricingCurve(
    _maxIndex: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  setTreasury(
    _treasury: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  tokenIdToTxHash(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  tokenType(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  treasury(overrides?: CallOverrides): Promise<string>;

  txHashToTokenId(
    arg0: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  staticCall: {
    maxIndex(overrides?: CallOverrides): Promise<BigNumber>;

    mint(
      _dst: string,
      _txHash: BigNumberish,
      overrides?: PayableOverrides,
    ): Promise<void>;

    mintableErc1155(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    pobMinterV1(overrides?: CallOverrides): Promise<string>;

    pricingCurve(
      _maxIndex: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<void>;

    setTreasury(_treasury: string, overrides?: Overrides): Promise<void>;

    tokenIdToTxHash(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    tokenType(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(newOwner: string, overrides?: Overrides): Promise<void>;

    treasury(overrides?: CallOverrides): Promise<string>;

    txHashToTokenId(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null,
    ): EventFilter;

    UpdatedRegistry(tokenId: null, txHash: null): EventFilter;
  };

  estimateGas: {
    maxIndex(): Promise<BigNumber>;
    mint(_dst: string, _txHash: BigNumberish): Promise<BigNumber>;
    mintableErc1155(): Promise<BigNumber>;
    owner(): Promise<BigNumber>;
    pobMinterV1(): Promise<BigNumber>;
    pricingCurve(_maxIndex: BigNumberish): Promise<BigNumber>;
    renounceOwnership(): Promise<BigNumber>;
    setTreasury(_treasury: string): Promise<BigNumber>;
    tokenIdToTxHash(arg0: BigNumberish): Promise<BigNumber>;
    tokenType(): Promise<BigNumber>;
    transferOwnership(newOwner: string): Promise<BigNumber>;
    treasury(): Promise<BigNumber>;
    txHashToTokenId(arg0: BigNumberish): Promise<BigNumber>;
  };

  populateTransaction: {
    maxIndex(): Promise<PopulatedTransaction>;
    mint(_dst: string, _txHash: BigNumberish): Promise<PopulatedTransaction>;
    mintableErc1155(): Promise<PopulatedTransaction>;
    owner(): Promise<PopulatedTransaction>;
    pobMinterV1(): Promise<PopulatedTransaction>;
    pricingCurve(_maxIndex: BigNumberish): Promise<PopulatedTransaction>;
    renounceOwnership(): Promise<PopulatedTransaction>;
    setTreasury(_treasury: string): Promise<PopulatedTransaction>;
    tokenIdToTxHash(arg0: BigNumberish): Promise<PopulatedTransaction>;
    tokenType(): Promise<PopulatedTransaction>;
    transferOwnership(newOwner: string): Promise<PopulatedTransaction>;
    treasury(): Promise<PopulatedTransaction>;
    txHashToTokenId(arg0: BigNumberish): Promise<PopulatedTransaction>;
  };
}
