/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from 'ethers';
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from '@ethersproject/contracts';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';

interface WhitelistExchangesProxyInterface extends ethers.utils.Interface {
  functions: {
    'isAddressWhitelisted(address)': FunctionFragment;
    'owner()': FunctionFragment;
    'paused()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setPaused(bool)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'updateProxyAddress(address,bool)': FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: 'isAddressWhitelisted',
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: void): string;
  encodeFunctionData(functionFragment: 'paused', values?: void): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: void,
  ): string;
  encodeFunctionData(functionFragment: 'setPaused', values: [boolean]): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'updateProxyAddress',
    values: [string, boolean],
  ): string;

  decodeFunctionResult(
    functionFragment: 'isAddressWhitelisted',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'setPaused', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'updateProxyAddress',
    data: BytesLike,
  ): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
}

export class WhitelistExchangesProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: WhitelistExchangesProxyInterface;

  functions: {
    isAddressWhitelisted(
      proxy: string,
      overrides?: CallOverrides,
    ): Promise<{
      0: boolean;
    }>;

    owner(
      overrides?: CallOverrides,
    ): Promise<{
      0: string;
    }>;

    paused(
      overrides?: CallOverrides,
    ): Promise<{
      0: boolean;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    setPaused(
      newPaused: boolean,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;

    updateProxyAddress(
      proxy: string,
      status: boolean,
      overrides?: Overrides,
    ): Promise<ContractTransaction>;
  };

  isAddressWhitelisted(
    proxy: string,
    overrides?: CallOverrides,
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  setPaused(
    newPaused: boolean,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  updateProxyAddress(
    proxy: string,
    status: boolean,
    overrides?: Overrides,
  ): Promise<ContractTransaction>;

  staticCall: {
    isAddressWhitelisted(
      proxy: string,
      overrides?: CallOverrides,
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: Overrides): Promise<void>;

    setPaused(newPaused: boolean, overrides?: Overrides): Promise<void>;

    transferOwnership(newOwner: string, overrides?: Overrides): Promise<void>;

    updateProxyAddress(
      proxy: string,
      status: boolean,
      overrides?: Overrides,
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null,
    ): EventFilter;
  };

  estimateGas: {
    isAddressWhitelisted(proxy: string): Promise<BigNumber>;
    owner(): Promise<BigNumber>;
    paused(): Promise<BigNumber>;
    renounceOwnership(): Promise<BigNumber>;
    setPaused(newPaused: boolean): Promise<BigNumber>;
    transferOwnership(newOwner: string): Promise<BigNumber>;
    updateProxyAddress(proxy: string, status: boolean): Promise<BigNumber>;
  };

  populateTransaction: {
    isAddressWhitelisted(proxy: string): Promise<PopulatedTransaction>;
    owner(): Promise<PopulatedTransaction>;
    paused(): Promise<PopulatedTransaction>;
    renounceOwnership(): Promise<PopulatedTransaction>;
    setPaused(newPaused: boolean): Promise<PopulatedTransaction>;
    transferOwnership(newOwner: string): Promise<PopulatedTransaction>;
    updateProxyAddress(
      proxy: string,
      status: boolean,
    ): Promise<PopulatedTransaction>;
  };
}
